### ISSUE TITLE
index typography

### ISSUE THREAD

**Issue by serogd** [prophet12505/Project-Winter-Seasonal-Event#22]
I feel it is redundant if we put "hours" "minutes" and "seconds" . I vote we keep "days" but the rest be taken out because the countdown as laid out on the index is already intuitive with the seconds moving every second and days separated. For the rest of the pages, I suggest there be no typography on the countdown at all because the user would have already seen it on the index when they get to the website.

**Comment by prophet12505** [comment]
D o n e
